version: "3.9"
services:
  minecraft:
    image: openjdk:17
    restart: unless-stopped
    ports:
      - "25565:25565"
      - "8123:8123"
      - "19132:19132"
      - "19133:19133"
    tty: true
    stdin_open: true
    working_dir: /data
    volumes:
      - /home/minecraft:/data
    environment:
      - WORKDIR=/data
      - BASE_DIR=/data
    command: java -Xmx5024M -Xms5024M -jar craftserver.jar nogui
